name: "Continuous Integration"

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install PostgreSQL
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y -qq postgresql postgresql-client
        sudo systemctl restart postgresql
        sudo -u postgres createuser -s runner
    - name: Install dependencies
      run: ./install_dependencies.sh
    - name: Create database
      run: createdb wikiprocessingdb
    - name: Build for languages Limburgish (li), Bavarian (bar)
      run: |
        LATEST_DATE=$(./steps/latest_available_data.sh)
        export WIKIPEDIA_DATE=$LATEST_DATE
        export WIKIDATA_DATE=$LATEST_DATE

        ./steps/wikipedia_download.sh
        ./steps/wikipedia_sql2csv.sh
        ./steps/wikipedia_import.sh
        ./steps/wikipedia_process.sh

        grep county config/wikidata_place_types.txt > new.txt
        mv new.txt config/wikidata_place_types.txt
        ./steps/wikidata_api_fetch_placetypes.sh
      env:
        BUILDID: ci_test_build
        LANGUAGES: li,bar

    - name: Test output
      run: tests/run.sh
